<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityGateway;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Gateways\Pagination;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntitiesRequest;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityListItemResponseAssembler;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\PaginatedUseCaseResponse;
use OpenClassrooms\UseCase\BusinessRules\Entities\PaginatedCollection;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCase;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

class GetFunctionalEntities implements UseCase
{
    /**
     * @var FunctionalEntityGateway
     */
    private $gateway;

    /**
     * @var FunctionalEntityListItemResponseAssembler
     */
    private $responseAssembler;

    public function __construct(FunctionalEntityGateway $gateway, FunctionalEntityListItemResponseAssembler $assembler)
    {
        $this->gateway = $gateway;
        $this->responseAssembler = $assembler;
    }

    /**
     * @param GetFunctionalEntitiesRequest $useCaseRequest
     */
    public function execute(UseCaseRequest $useCaseRequest): PaginatedUseCaseResponse
    {
        $functionalEntities = $this->getFunctionalEntities(
            $useCaseRequest->getFilters(),
            $useCaseRequest->getSorts(),
            $this->getPagination($useCaseRequest->getPage(), $useCaseRequest->getItemsPerPage())
        );

        return $this->buildResponse($functionalEntities);
    }

    private function getFunctionalEntities(array $filters, array $sorts, array $pagination): PaginatedCollection
    {
        return $this->gateway->findAll($filters, $sorts, $pagination);
    }

    private function getPagination(int $page, int $itemPerPage): array
    {
        return [
            Pagination::PAGE           => $page,
            Pagination::ITEMS_PER_PAGE => $itemPerPage,
        ];
    }

    private function buildResponse(PaginatedCollection $functionalEntities): PaginatedUseCaseResponse
    {
        return $this->responseAssembler->createPaginatedCollection($functionalEntities);
    }
}
