#!/bin/bash

diffPhpFiles="$(git diff --stat --cached origin/master --name-only | grep '\.php*$')"
totalModifiedPHPFiles="${#diffPhpFiles}"

if [ "$totalModifiedPHPFiles" -eq 0 ]; then
    echo "✔ No PHP files have been commited."
    exit 0
fi

output="$(vendor/phpunit/phpunit/phpunit -c phpunit.xml -vvv)";

if [[ $? = 0 ]]; then
  echo "✔ All checks passed with success."
  exit 0
else
  echo "$output"
  echo "✘ Tests have failed, push aborted."
  exit 1
fi
