<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\SkeletonModels\BusinessRules\UseCases;

use OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\UseCases\Impl\CreateEntityUseCaseRequestDTOSkeletonModelAssemblerImpl;

class CreateEntityUseCaseRequestDTOSkeletonModelAssemblerMock extends CreateEntityUseCaseRequestDTOSkeletonModelAssemblerImpl
{
}
