<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
interface GetEntityRequestBuilder
{
    public function create(): GetEntityRequestBuilder;

    public function withId(int $id): GetEntityRequestBuilder;

    public function build(): GetEntityRequest;
}
