language: php

sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

before_script:
  - composer install --no-scripts --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

before_cache:
  - bash <(curl -s https://codecov.io/bash)
