<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\DeleteFunctionalEntityRequest;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\DeleteFunctionalEntityRequestBuilder;

class DeleteFunctionalEntityRequestBuilderImpl implements DeleteFunctionalEntityRequestBuilder
{
    /**
     * @var int
     */
    private $functionalEntityId;

    public function build(): DeleteFunctionalEntityRequest
    {
        return new DeleteFunctionalEntityRequestDTO($this->functionalEntityId);
    }

    public function create(): DeleteFunctionalEntityRequestBuilder
    {
        return $this;
    }

    public function withFunctionalEntityId(int $id): DeleteFunctionalEntityRequestBuilder
    {
        $this->functionalEntityId = $id;

        return $this;
    }
}
