<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\EditFunctionalEntityRequest;

final class EditFunctionalEntityRequestDTO implements EditFunctionalEntityRequest
{
    use FunctionalEntityCommonRequest;

    public bool $field1Updated = false;

    public bool $field2Updated = false;

    public bool $field3Updated = false;

    public bool $field4Updated = false;

    public int $functionalEntityId;

    public function getFunctionalEntityId(): int
    {
        return $this->functionalEntityId;
    }

    public function isField1Updated(): bool
    {
        return $this->field1Updated;
    }

    public function isField2Updated(): bool
    {
        return $this->field2Updated;
    }

    public function isField3Updated(): bool
    {
        return $this->field3Updated;
    }

    public function isField4Updated(): bool
    {
        return $this->field4Updated;
    }
}
