<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

trait FunctionalEntityCommonRequest
{
    public string $field1;

    /**
     * @var string[]
     */
    public array $field2;

    public bool $field3;

    public \DateTimeInterface $field4;

    public function getField1(): string
    {
        return $this->field1;
    }

    /**
     * @return string[]
     */
    public function getField2(): array
    {
        return $this->field2;
    }

    public function getField4(): \DateTimeInterface
    {
        return $this->field4;
    }

    public function isField3(): bool
    {
        return $this->field3;
    }
}
