<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntityRequest;

/**
 * @author authorStub <author.stub@example.com>
 */
class GetFunctionalEntityRequestDTO implements GetFunctionalEntityRequest
{
    /**
     * @var int
     */
    public $id;

    public function getFunctionalEntityId(): int
    {
        return $this->id;
    }
}
