<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Gateways\Pagination;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntitiesRequest;

final class GetFunctionalEntitiesRequestDTO implements GetFunctionalEntitiesRequest
{
    /**
     * @var string[]
     */
    public $filters = [];

    /**
     * @var int
     */
    public $itemsPerPage;

    /**
     * @var int
     */
    public $page = Pagination::DEFAULT_PAGE_NUMBER;

    /**
     * @var string[]
     */
    public $sorts = [];

    /**
     * {@inheritdoc}
     */
    public function getFilters(): array
    {
        return $this->filters;
    }

    public function getItemsPerPage(): int
    {
        return $this->itemsPerPage;
    }

    public function getPage(): int
    {
        return $this->page;
    }

    /**
     * {@inheritdoc}
     */
    public function getSorts(): array
    {
        return $this->sorts;
    }
}
