<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetGenericUseCaseRequest;

/**
 * @author authorStub <author.stub@example.com>
 */
class GetGenericUseCaseRequestDTO implements GetGenericUseCaseRequest
{
    /**
     * @var int
     */
    public $id;

    public function getGenericUseCaseId(): int
    {
        return $this->id;
    }
}
