<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetGenericUseCaseRequest;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetGenericUseCaseRequestBuilder;

/**
 * @author authorStub <author.stub@example.com>
 */
class GetGenericUseCaseRequestBuilderImpl implements GetGenericUseCaseRequestBuilder
{
    /**
     * @var GetGenericUseCaseRequestDTO
     */
    private $request;

    public function create(): GetGenericUseCaseRequestBuilder
    {
        $this->request = new GetGenericUseCaseRequestDTO();

        return $this;
    }

    public function withGenericUseCaseId(int $id): GetGenericUseCaseRequestBuilder
    {
        $this->request->id = $id;

        return $this;
    }

    public function build(): GetGenericUseCaseRequest
    {
        return $this->request;
    }
}
