<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetGenericUseCasesRequest;

/**
 * @author authorStub <author.stub@example.com>
 */
class GetGenericUseCasesRequestDTO implements GetGenericUseCasesRequest
{
    /**
     * @var string[]
     */
    public $filters = [];

    /**
     * @var int
     */
    public $itemsPerPage;

    /**
     * @var int
     */
    public $page = Pagination::DEFAULT_PAGE_NUMBER;

    /**
     * @var string[]
     */
    public $sorts = [];

    /**
     * {@inheritdoc}
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * {@inheritdoc}
     */
    public function getItemsPerPage(): int
    {
        return $this->itemsPerPage;
    }

    /**
     * {@inheritdoc}
     */
    public function getPage(): int
    {
        return $this->page;
    }

    /**
     * {@inheritdoc}
     */
    public function getSorts()
    {
        return $this->sorts;
    }
}
