<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetGenericUseCasesRequest;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetGenericUseCasesRequestBuilder;

/**
 * @author authorStub <author.stub@example.com>
 */
class GetGenericUseCasesRequestBuilderImpl implements GetGenericUseCasesRequestBuilder
{
    /**
     * @var GetGenericUseCasesRequestDTO
     */
    private $request;

    public function create(): GetGenericUseCasesRequestBuilder
    {
        $this->request = new GetGenericUseCasesRequestDTO();

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function withFilters(array $filters = []): GetGenericUseCasesRequestBuilder
    {
        $this->request->filters = $filters;

        return $this;
    }

    public function withItemsPerPage(int $itemsPerPage): GetGenericUseCasesRequestBuilder
    {
        $this->request->itemsPerPage = $itemsPerPage;

        return $this;
    }

    public function withPage(int $page = 1): GetGenericUseCasesRequestBuilder
    {
        $this->request->page = $page;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function withSort(array $sort = []): GetGenericUseCasesRequestBuilder
    {
        $this->request->sorts = $sort;

        return $this;
    }

    public function build(): GetGenericUseCasesRequest
    {
        return $this->request;
    }
}
