<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\ViewModels\Web\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityResponse;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
trait FunctionalEntityAssemblerTrait
{
    protected function hydrateCommonFields(FunctionalEntity $vm, FunctionalEntityResponse $functionalEntity)
    {
        $vm->id = $functionalEntity->getId();
        $vm->field1 = $functionalEntity->getField1();
        $vm->field2 = $functionalEntity->getField2();
        $vm->field3 = $functionalEntity->isField3();
    }
}
