<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\BusinessRules\Entities\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl\FunctionalEntityImpl;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityStub1 extends FunctionalEntityImpl
{
    const FIELD_1 = 'Functional Entity Stub 1 field 1';

    const FIELD_2 = ['Functional Entity Stub 1 field 2 1', 'Functional Entity Stub 1 field 2 2'];

    const FIELD_3 = true;

    const ID = 1;
}
