<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl\FunctionalEntityImpl;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityListItemResponseStub1;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityStub1 extends FunctionalEntityImpl
{
    const FIELD_1 = FunctionalEntityListItemResponseStub1::FIELD_1;

    const FIELD_2 = FunctionalEntityListItemResponseStub1::FIELD_2;

    const FIELD_3 = FunctionalEntityListItemResponseStub1::FIELD_3;

    const ID = FunctionalEntityListItemResponseStub1::ID;
}
