<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Entities\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\App\Entity\Domain\SubDomain\FunctionalEntityImpl;

class FunctionalEntityStub2 extends FunctionalEntityImpl
{
    public const FIELD_1 = 'Functional Entity Stub 2 field 1';

    public const FIELD_2 = ['Functional Entity Stub 2 field 2 1', 'Functional Entity Stub 2 field 2 2'];

    public const FIELD_3 = true;

    public const FIELD_4 = '2018-01-01';

    public const ID = 2;

    public const UPDATED_AT = '2018-01-01';

    protected string $field1 = self::FIELD_1;

    protected array $field2 = self::FIELD_2;

    protected bool $field3 = self::FIELD_3;

    protected int $id = self::ID;

    public function __construct()
    {
        $this->field4 = new \DateTimeImmutable(self::FIELD_4);
        $this->updatedAt = new \DateTimeImmutable(self::UPDATED_AT);
    }
}
