<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\ViewModels\Web\Domain\SubDomain\Impl;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\ViewModels\Web\Domain\SubDomain\FunctionalEntityAssemblerTrait;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\ViewModels\Web\Domain\SubDomain\FunctionalEntityDetail;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\ViewModels\Web\Domain\SubDomain\FunctionalEntityDetailAssembler;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class FunctionalEntityDetailAssemblerImpl implements FunctionalEntityDetailAssembler
{
    use FunctionalEntityAssemblerTrait;

    public function createDetail(FunctionalEntityDetailResponse $functionalEntity): FunctionalEntityDetail
    {
        $vm = new FunctionalEntityDetailImpl();
        $this->hydrateCommonFields($vm, $functionalEntity);

        return $vm;
    }
}
