<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl\FunctionalEntityViewModelDetailImpl;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseStub1;

class FunctionalEntityViewModelDetailStub1 extends FunctionalEntityViewModelDetailImpl
{
    public const FIELD_1 = FunctionalEntityDetailResponseStub1::FIELD_1;

    public const FIELD_2 = FunctionalEntityDetailResponseStub1::FIELD_2;

    public const FIELD_3 = FunctionalEntityDetailResponseStub1::FIELD_3;

    public const FIELD_4 = FunctionalEntityDetailResponseStub1::FIELD_4;

    public const ID = FunctionalEntityDetailResponseStub1::ID;

    /**
     * {@inheritdoc}
     */
    public $field1 = self::FIELD_1;

    /**
     * {@inheritdoc}
     */
    public $field2 = self::FIELD_2;

    /**
     * {@inheritdoc}
     */
    public $field3 = self::FIELD_3;

    /**
     * {@inheritdoc}
     */
    public $id = self::ID;

    public function __construct()
    {
        $this->field4 = new \DateTimeImmutable(self::FIELD_4);
    }
}
