<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl\FunctionalEntityDetailImpl;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseStub1;

class FunctionalEntityDetailStub1 extends FunctionalEntityDetailImpl
{
    const FIELD_1 = FunctionalEntityDetailResponseStub1::FIELD_1;

    const FIELD_2 = FunctionalEntityDetailResponseStub1::FIELD_2;

    const FIELD_3 = FunctionalEntityDetailResponseStub1::FIELD_3;

    const FIELD_4 = FunctionalEntityDetailResponseStub1::FIELD_4;

    const ID = FunctionalEntityDetailResponseStub1::ID;

    /**
     * {@inheritdoc}
     */
    public $field1 = self::FIELD_1;

    /**
     * {@inheritdoc}
     */
    public $field2 = self::FIELD_2;

    /**
     * {@inheritdoc}
     */
    public $field3 = self::FIELD_3;

    /**
     * {@inheritdoc}
     */
    public $id = self::ID;

    public function __construct()
    {
        $this->field4 = new \DateTimeImmutable(self::FIELD_4);
    }
}
