<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelListItem;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityListItemResponseStub1;

final class FunctionalEntityViewModelListItemStub1 extends FunctionalEntityViewModelListItem
{
    public const FIELD_1 = FunctionalEntityListItemResponseStub1::FIELD_1;

    public const FIELD_2 = FunctionalEntityListItemResponseStub1::FIELD_2;

    public const FIELD_3 = FunctionalEntityListItemResponseStub1::FIELD_3;

    public const ID = FunctionalEntityListItemResponseStub1::ID;

    public $field1 = self::FIELD_1;

    public $field2 = self::FIELD_2;

    public $field3 = self::FIELD_3;

    public $id = self::ID;
}
