<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModel;
use PHPUnit\Framework\Assert;

trait FunctionalEntityViewModelTestCase
{
    public function assertFunctionalEntityViewModel(FunctionalEntityViewModel $expected, FunctionalEntityViewModel $actual): void
    {
        Assert::assertSame($expected->id, $actual->id);
        Assert::assertSame($expected->field1, $actual->field1);
        Assert::assertSame($expected->field2, $actual->field2);
        Assert::assertSame($expected->field3, $actual->field3);
    }
}
