<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelDetail;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseStub1;

final class FunctionalEntityViewModelDetailStub1 extends FunctionalEntityViewModelDetail
{
    public const FIELD_1 = FunctionalEntityDetailResponseStub1::FIELD_1;

    public const FIELD_2 = FunctionalEntityDetailResponseStub1::FIELD_2;

    public const FIELD_3 = FunctionalEntityDetailResponseStub1::FIELD_3;

    public const FIELD_4 = FunctionalEntityDetailResponseStub1::FIELD_4;

    public const ID = FunctionalEntityDetailResponseStub1::ID;

    public string $field1 = self::FIELD_1;

    public array $field2 = self::FIELD_2;

    public bool $field3 = self::FIELD_3;

    public int $id = self::ID;

    public function __construct()
    {
        $this->field4 = new \DateTimeImmutable(self::FIELD_4);
    }
}
