<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntity;
use PHPUnit\Framework\Assert;

/**
 * @author authorStub <author.stub@example.com>
 */
trait FunctionalEntityTestCase
{
    public function assertFunctionalEntityTestCase(FunctionalEntity $expected, FunctionalEntity $actual): void
    {
        Assert::assertSame($expected->id, $actual->id);
        Assert::assertSame($expected->field1, $actual->field1);
        Assert::assertSame($expected->field2, $actual->field2);
        Assert::assertSame($expected->field3, $actual->field3);
    }
}
