<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl\FunctionalEntityImpl;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityStub1 extends FunctionalEntityImpl
{
    const FIELD_1 = FunctionalEntityResponseStub1::FIELD_1;

    const FIELD_2 = FunctionalEntityResponseStub1::FIELD_2;

    const FIELD_3 = FunctionalEntityResponseStub1::FIELD_3;

    const ID = FunctionalEntityResponseStub1::ID;
}
