<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\Api\ViewModels\Domain\SubDomain;

/**
 * @author authorStub <author.stub@example.com>
 */
abstract class FunctionalEntityListItemStub1 extends FunctionalEntityListItemImpl
{
    const FIELD_1 = FunctionalEntityListItemResponseStub1::FIELD_1;

    const FIELD_2 = FunctionalEntityListItemResponseStub1::FIELD_2;

    const FIELD_3 = FunctionalEntityListItemResponseStub1::FIELD_3;

    const ID = FunctionalEntityListItemResponseStub1::ID;

    /**
     * {@inheritdoc}
     */
    public $field1 = self::FIELD_1;

    /**
     * {@inheritdoc}
     */
    public $field2 = self::FIELD_2;

    /**
     * {@inheritdoc}
     */
    public $field3 = self::FIELD_3;

    /**
     * {@inheritdoc}
     */
    public $id = self::ID;
}
