<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelAssemblerTrait;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelDetail;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelDetailAssembler;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;

class FunctionalEntityViewModelDetailAssemblerImpl extends FunctionalEntityViewModelDetailAssembler
{
    use FunctionalEntityViewModelAssemblerTrait;

    public function create(FunctionalEntityDetailResponse $functionalEntityDetailResponse): FunctionalEntityViewModelDetail
    {
        $vm = new FunctionalEntityViewModelDetailImpl();
        $this->hydrateCommonFields($vm, $functionalEntityDetailResponse);
        $vm->field4 = $functionalEntityDetailResponse->getField4();

        return $vm;
    }
}
