<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelAssemblerTrait;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelListItem;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelListItemAssembler;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityResponse;

class FunctionalEntityViewModelListItemAssemblerImpl implements FunctionalEntityViewModelListItemAssembler
{
    use FunctionalEntityViewModelAssemblerTrait;

    /**
     * @inheritdoc
     */
    public function createListItems(array $functionalEntities): array
    {
        $vms = [];
        foreach ($functionalEntities as $functionalEntity) {
            $vms[] = $this->createListItem($functionalEntity);
        }

        return $vms;
    }

    /**
     * @return FunctionalEntityViewModelListItemImpl
     */
    private function createListItem(FunctionalEntityResponse $functionalEntity): FunctionalEntityViewModelListItem
    {
        $vm = new FunctionalEntityViewModelListItemImpl();
        $this->hydrateCommonFields($vm, $functionalEntity);

        return $vm;
    }
}
