<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\Impl;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityAssemblerTrait;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityListItem;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityListItemAssembler;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityResponse;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityListItemAssemblerImpl implements FunctionalEntityListItemAssembler
{
    use FunctionalEntityAssemblerTrait;

    /**
     * @inheritdoc
     */
    public function createListItems(array $functionalEntities): array
    {
        $vms = [];
        foreach ($functionalEntities as $functionalEntity) {
            $vms[] = $this->createListItem($functionalEntity);
        }

        return $vms;
    }

    /**
     * @return FunctionalEntityListItemImpl
     */
    private function createListItem(FunctionalEntityResponse $functionalEntity): FunctionalEntityListItem
    {
        $vm = new FunctionalEntityListItemImpl();
        $this->hydrateCommonFields($vm, $functionalEntity);

        return $vm;
    }
}
