<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\Controller\Domain\SubDomain;

use OC\ApiBundle\Framework\FrameworkBundle\Controller\AbstractApiController;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModel;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelDetailAssembler;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Gateways\Domain\SubDomain\Exceptions\FunctionalEntityNotFoundException;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntityRequestBuilder;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\GetFunctionalEntity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class GetFunctionalEntityController extends AbstractApiController
{
    /**
     * @var FunctionalEntityViewModelDetailAssembler
     */
    private $functionalEntityViewModelDetailAssembler;

    /**
     * @var GetFunctionalEntityRequestBuilder
     */
    private $getFunctionalEntityRequestBuilder;

    public function __construct(
        FunctionalEntityViewModelDetailAssembler $assembler,
        GetFunctionalEntityRequestBuilder $builder
    ) {
        $this->functionalEntityViewModelDetailAssembler = $assembler;
        $this->getFunctionalEntityRequestBuilder = $builder;
    }

    /**
     * @Security("")
     * @throws NotFoundHttpException
     */
    public function getAction(int $functionalEntity): JsonResponse
    {
        try {
            $functionalEntity = $this->getFunctionalEntity($functionalEntity);
            $vm = $this->buildViewModel($functionalEntity);

            return $this->createJsonResponse($vm);
        } catch (FunctionalEntityNotFoundException $e) {
            $this->throwNotFoundException();
        }
    }

    /**
     * @throws FunctionalEntityNotFoundException
     */
    private function getFunctionalEntity(int $functionalEntityId): FunctionalEntityDetailResponse
    {
        return $this->get(GetFunctionalEntity::class)->execute(
            $this->getFunctionalEntityRequestBuilder
                ->create()
                ->withFunctionalEntityId($functionalEntityId)
                ->build()
        );
    }

    protected function buildViewModel(FunctionalEntityDetailResponse $functionalEntity): FunctionalEntityViewModel
    {
        return $this->functionalEntityViewModelDetailAssembler->create($functionalEntity);
    }
}
