<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\Controller\Domain\SubDomain;

use Carbon\CarbonImmutable;
use OC\ApiBundle\Framework\FrameworkBundle\Controller\AbstractApiController;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\Models\Domain\SubDomain\PostFunctionalEntityModel;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelDetail;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain\FunctionalEntityViewModelDetailAssembler;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\CreateFunctionalEntity;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\Request\CreateFunctionalEntityRequest;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCase;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class PostFunctionalEntityController extends AbstractApiController
{
    private FunctionalEntityViewModelDetailAssembler $functionalEntityViewModelDetailAssembler;

    /** @var UseCase|CreateFunctionalEntity */
    private UseCase $createFunctionalEntity;

    public function __construct(
        FunctionalEntityViewModelDetailAssembler $assembler,
        UseCase $createFunctionalEntity
    ) {
        $this->functionalEntityViewModelDetailAssembler = $assembler;
        $this->createFunctionalEntity = $createFunctionalEntity;
    }

    /**
     * @Route("/functional-entities", name="openclassrooms_codegenerator_tests_fixtures_classes_api_sub_domain_functional_entity_post", methods={"POST"})
     *
     * @Security("")
     */
    public function __invoke(): JsonResponse
    {
        /** @var PostFunctionalEntityModel $model */
        $model = $this->getModelFromRequest(PostFunctionalEntityModel::class);
        $response = $this->createFunctionalEntity($model);

        return $this->createCreatedResponse($this->generateLocationUrl($response), $this->buildViewModel($response));
    }

    private function createFunctionalEntity(PostFunctionalEntityModel $model): FunctionalEntityDetailResponse
    {
        return $this->createFunctionalEntity->execute(
            CreateFunctionalEntityRequest::create()
                ->withField1($model->field1)
                ->withField2($model->field2)
                ->withField3($model->field3)
                ->withField4(new CarbonImmutable($model->field4))
        );
    }

    private function generateLocationUrl(FunctionalEntityDetailResponse $response): string
    {
        return $this->generateUrl('openclassrooms_codegenerator_tests_fixtures_classes_api_sub_domain_functional_entity_post', ['functionalEntityId' => $response->getId()]);
    }

    private function buildViewModel(FunctionalEntityDetailResponse $response): FunctionalEntityViewModelDetail
    {
        return $this->functionalEntityViewModelDetailAssembler->create($response);
    }
}
