<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\SkeletonModels\Tests\Doubles\BusinessRules\Responders;

use OpenClassrooms\CodeGenerator\SkeletonModels\Tests\Doubles\BusinessRules\Responders\Impl\UseCaseListItemResponseTestCaseSkeletonModelAssemblerImpl;

class UseCaseListItemResponseTestCaseSkeletonModelAssemblerMock extends UseCaseListItemResponseTestCaseSkeletonModelAssemblerImpl
{
}
