<?php

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities\Type;

final class EntityFileObjectType
{
    public const BUSINESS_RULES_ENTITY                     = 'BUSINESS_RULES_ENTITY';

    public const BUSINESS_RULES_ENTITY_FACTORY             = 'BUSINESS_RULES_ENTITY_FACTORY';

    public const BUSINESS_RULES_ENTITY_FACTORY_IMPL        = 'BUSINESS_RULES_ENTITY_FACTORY_IMPL';

    public const BUSINESS_RULES_ENTITY_GATEWAY             = 'BUSINESS_RULES_ENTITY_GATEWAY';

    public const BUSINESS_RULES_ENTITY_IMPL                = 'BUSINESS_RULES_ENTITY_IMPL';

    public const BUSINESS_RULES_ENTITY_IN_MEMORY_GATEWAY   = 'BUSINESS_RULES_ENTITY_IN_MEMORY_GATEWAY';

    public const BUSINESS_RULES_ENTITY_NOT_FOUND_EXCEPTION = 'BUSINESS_RULES_ENTITY_EXCEPTION';

    public const BUSINESS_RULES_ENTITY_REPOSITORY          = 'BUSINESS_RULES_ENTITY_REPOSITORY';

    public const BUSINESS_RULES_ENTITY_STUB                = 'BUSINESS_RULES_ENTITY_STUB';
}
