<?php

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities\Type;

final class UseCaseRequestFileObjectType
{
    // CREATE
    public const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST              = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST';

    public const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER      = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER';

    public const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL';

    public const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_DTO          = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_DTO';

    public const BUSINESS_RULES_CREATE_REQUEST_TRAIT                        = 'BUSINESS_RULES_CREATE_REQUEST_TRAIT';

    // DELETE
    public const BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST              = 'BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST';

    public const BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST_BUILDER      = 'BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST_BUILDER';

    public const BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL';

    public const BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST_DTO          = 'BUSINESS_RULES_DELETE_ENTITY_USE_CASE_REQUEST_DTO';

    // EDIT
    public const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST              = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST';

    public const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER      = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER';

    public const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL';

    public const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_DTO          = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_DTO';

    public const BUSINESS_RULES_ENTITY_USE_CASE_COMMON_REQUEST            = 'BUSINESS_RULES_ENTITY_USE_CASE_COMMON_REQUEST';

    // GET ALL
    public const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST              = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST';

    public const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER      = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER';

    public const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER_IMPL';

    public const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_DTO          = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_DTO';

    // GET
    public const BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST              = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST';

    // USE CASE
    public const BUSINESS_RULES_USE_CASE_REQUEST              = 'BUSINESS_RULES_USE_CASE_REQUEST';
}
