<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities\Type;

/**
 * @author Samuel Gomis <samuel.gomis@external.openclassrooms.com>
 */
final class UseCaseFileObjectType
{
    const BUSINESS_RULES_GET_ENTITIES_USE_CASE = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE';

    const BUSINESS_RULES_GET_ENTITIES_USE_CASE_TEST = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_TEST';

    const BUSINESS_RULES_GET_ENTITY_USE_CASE = 'BUSINESS_RULES_GET_ENTITY_USE_CASE';

    const BUSINESS_RULES_GET_ENTITY_USE_CASE_TEST = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_TEST';

    const BUSINESS_RULES_USE_CASE = 'BUSINESS_RULES_USE_CASE';

    const BUSINESS_RULES_USE_CASE_TEST = 'BUSINESS_RULES_USE_CASE_TEST';
}
