<?php

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities\Type;

final class UseCaseFileObjectType
{
    public const BUSINESS_RULES_CREATE_ENTITY_USE_CASE      = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE';

    public const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_TEST = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_TEST';

    public const BUSINESS_RULES_DELETE_ENTITY_USE_CASE      = 'BUSINESS_RULES_DELETE_ENTITY_USE_CASE';

    public const BUSINESS_RULES_DELETE_ENTITY_USE_CASE_TEST = 'BUSINESS_RULES_DELETE_ENTITY_USE_CASE_TEST';

    public const BUSINESS_RULES_EDIT_ENTITY_USE_CASE        = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE';

    public const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_TEST   = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_TEST';

    public const BUSINESS_RULES_GET_ENTITIES_USE_CASE       = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE';

    public const BUSINESS_RULES_GET_ENTITIES_USE_CASE_TEST  = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_TEST';

    public const BUSINESS_RULES_GET_ENTITY_USE_CASE         = 'BUSINESS_RULES_GET_ENTITY_USE_CASE';

    public const BUSINESS_RULES_GET_ENTITY_USE_CASE_TEST    = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_TEST';

    public const BUSINESS_RULES_USE_CASE                    = 'BUSINESS_RULES_USE_CASE';

    public const BUSINESS_RULES_USE_CASE_TEST               = 'BUSINESS_RULES_USE_CASE_TEST';
}
