<?php

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities\Type;

final class UseCaseResponseFileObjectType
{
    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE                   = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE';

    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER         = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER';

    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER_IMPL    = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER_IMPL';

    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER_MOCK    = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER_MOCK';

    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_DTO               = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_DTO';

    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_STUB              = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_STUB';

    public const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_TEST_CASE         = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_TEST_CASE';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE                = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER      = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER_IMPL = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER_IMPL';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER_MOCK = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER_MOCK';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_DTO            = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_DTO';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_STUB           = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_STUB';

    public const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_TEST_CASE      = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_TEST_CASE';

    public const BUSINESS_RULES_USE_CASE_RESPONSE                          = 'BUSINESS_RULES_USE_CASE_RESPONSE';

    public const BUSINESS_RULES_USE_CASE_RESPONSE_ASSEMBLER_TRAIT          = 'BUSINESS_RULES_USE_CASE_RESPONSE_ASSEMBLER_TRAIT';

    public const BUSINESS_RULES_USE_CASE_RESPONSE_COMMON_FIELD_TRAIT       = 'BUSINESS_RULES_USE_CASE_RESPONSE_COMMON_FIELD_TRAIT';

    public const BUSINESS_RULES_USE_CASE_RESPONSE_STUB                     = 'BUSINESS_RULES_USE_CASE_RESPONSE_STUB';

    public const BUSINESS_RULES_USE_CASE_RESPONSE_TEST_CASE                = 'BUSINESS_RULES_USE_CASE_RESPONSE_TEST_CASE';
}
