<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities\Type;

/**
 * @author Samuel Gomis <samuel.gomis@external.openclassrooms.com>
 */
final class UseCaseRequestFileObjectType
{
    // CREATE
    const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST';

    const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER';

    const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL';

    const BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_DTO = 'BUSINESS_RULES_CREATE_ENTITY_USE_CASE_REQUEST_DTO';

    // EDIT
    const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST';

    const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER';

    const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL';

    const BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_DTO = 'BUSINESS_RULES_EDIT_ENTITY_USE_CASE_REQUEST_DTO';

    // GET ALL
    const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST';

    const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER';

    const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_BUILDER_IMPL';

    const BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_DTO = 'BUSINESS_RULES_GET_ENTITIES_USE_CASE_REQUEST_DTO';

    // GET
    const BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST';

    const BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST_BUILDER = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST_BUILDER';

    const BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST_BUILDER_IMPL';

    const BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST_DTO = 'BUSINESS_RULES_GET_ENTITY_USE_CASE_REQUEST_DTO';

    // USE CASE
    const BUSINESS_RULES_USE_CASE_REQUEST = 'BUSINESS_RULES_USE_CASE_REQUEST';

    const BUSINESS_RULES_USE_CASE_REQUEST_BUILDER = 'BUSINESS_RULES_USE_CASE_REQUEST_BUILDER';

    const BUSINESS_RULES_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_USE_CASE_REQUEST_BUILDER_IMPL';

    const BUSINESS_RULES_USE_CASE_REQUEST_DTO = 'BUSINESS_RULES_USE_CASE_REQUEST_DTO';
}
