<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities;

/**
 * @author Samuel Gomis <samuel.gomis@external.openclassrooms.com>
 */
class UseCaseRequestFileObjectType
{
    const BUSINESS_RULES_GET_ENTITY_REQUEST = 'BUSINESS_RULES_GET_ENTITY_REQUEST';

    const BUSINESS_RULES_USE_CASE_REQUEST = 'BUSINESS_RULES_USE_CASE_REQUEST';

    const BUSINESS_RULES_USE_CASE_REQUEST_BUILDER = 'BUSINESS_RULES_USE_CASE_REQUEST_BUILDER';

    const BUSINESS_RULES_USE_CASE_REQUEST_BUILDER_IMPL = 'BUSINESS_RULES_USE_CASE_REQUEST_BUILDER_IMPL';

    const BUSINESS_RULES_USE_CASE_REQUEST_DTO = 'BUSINESS_RULES_USE_CASE_REQUEST_DTO';
}
