<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Entities;

/**
 * @author Samuel Gomis <samuel.gomis@external.openclassrooms.com>
 */
final class UseCaseResponseFileObjectType
{
    const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE';

    const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER';

    const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER_IMPL = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_ASSEMBLER_IMPL';

    const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_DTO = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_DTO';

    const BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_STUB = 'BUSINESS_RULES_USE_CASE_DETAIL_RESPONSE_STUB';

    const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE';

    const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER';

    const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER_IMPL = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_ASSEMBLER_IMPL';

    const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_DTO = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_DTO';

    const BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_STUB = 'BUSINESS_RULES_USE_CASE_LIST_ITEM_RESPONSE_STUB';

    const BUSINESS_RULES_USE_CASE_RESPONSE = 'BUSINESS_RULES_USE_CASE_RESPONSE';

    const BUSINESS_RULES_USE_CASE_RESPONSE_DTO = 'BUSINESS_RULES_USE_CASE_RESPONSE_DTO';

    const BUSINESS_RULES_USE_CASE_RESPONSE_STUB = 'BUSINESS_RULES_USE_CASE_RESPONSE_STUB';

    const BUSINESS_RULES_USE_CASE_RESPONSE_TRAIT = 'BUSINESS_RULES_USE_CASE_RESPONSE_TRAIT';
}
