<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\Repository\Domain\SubDomain;

use Doctrine\ORM\EntityRepository;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityGateway;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityNotFoundException;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class FunctionalEntityRepository extends EntityRepository implements FunctionalEntityGateway
{
    /**
     * {@inheritdoc}
     */
    public function find($id)
    {
        $functionalEntity = parent::find($id);
        if (null === $functionalEntity) {
            throw new FunctionalEntityNotFoundException($id);
        }

        return $functionalEntity;
    }
}
