<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\Exceptions;

/**
 * @author authorStub <author.stub@example.com>
 */
class GenericUseCaseNotFoundException
{
}
