<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\Responders\Impl;

use OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\Responders\UseCaseListItemResponseAssemblerSkeletonModel;

class UseCaseListItemResponseAssemblerSkeletonModelImpl extends UseCaseListItemResponseAssemblerSkeletonModel
{
}
