<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Entities\Domain\SubDomain\FunctionalEntity;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
interface FunctionalEntityDetailResponseAssembler
{
    public function create(FunctionalEntity $functionalEntity): FunctionalEntityDetailResponse;
}
