<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityResponse;

/**
 * @author Samuel Gomis <gomis.samuel@external.openclassrooms.com>
 */
trait FunctionalEntityAssemblerTrait
{
    public function hydrateCommonFields(FunctionalEntityResponse $entity, FunctionalEntity $vm)
    {
        $vm->id = $entity->getId();
        $vm->field1 = $entity->getField1();
        $vm->field2 = $entity->getField2();
        $vm->field3 = $entity->isField3();
    }
}
