<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityListItemResponse;

interface FunctionalEntityViewModelListItemAssembler
{
    /**
     * @param FunctionalEntityListItemResponse[] $functionalEntities
     *
     * @return FunctionalEntityViewModelListItem[]
     */
    public function createListItems(array $functionalEntities): array;
}
