<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

abstract class FunctionalEntityViewModel
{
    public string $field1;

    /**
     * @var string[]
     */
    public array $field2;

    public bool $field3;

    public int $id;
}
