<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

class FunctionalEntityViewModelDetail extends FunctionalEntityViewModel
{
    public \DateTimeInterface $field4;
}
