<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

use OC\BusinessRules\Utils\DtoCommonFieldsHydrator;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;

class FunctionalEntityViewModelDetailAssembler
{
    public function create(FunctionalEntityDetailResponse $functionalEntityDetailResponse): FunctionalEntityViewModelDetail
    {
        $vm = new FunctionalEntityViewModelDetail();
        DtoCommonFieldsHydrator::hydrate($vm, $functionalEntityDetailResponse);

        return $vm;
    }
}
