<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

/**
 * @author authorStub <author.stub@example.com>
 */
abstract class FunctionalEntityDetail extends FunctionalEntity
{
    /**
     * @var \DateTime
     */
    public $field4;
}
