<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;

/**
 * @author authorStub <author.stub@example.com>
 */
interface FunctionalEntityDetailAssembler
{
    public function create(FunctionalEntityDetailResponse $functionalEntityDetailResponse): FunctionalEntityDetail;
}
