<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Api\ViewModels\Domain\SubDomain;

abstract class FunctionalEntityViewModelDetail extends FunctionalEntityViewModel
{
    /**
     * @var \DateTimeImmutable
     */
    public $field4;
}
