<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\Requestors\Impl;

use OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\Requestors\GetEntitiesUseCaseRequestBuilderSkeletonModel;

class GetEntitiesUseCaseRequestBuilderSkeletonModelImpl extends GetEntitiesUseCaseRequestBuilderSkeletonModel
{
}
