<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\Request;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

final class CreateFunctionalEntityRequest implements UseCaseRequest
{
    public string $field1;

    /**
     * @var string[]
     */
    public array $field2;

    public bool $field3;

    public \DateTimeInterface $field4;

    public function getField1(): string
    {
        return $this->field1;
    }

    /**
     * @return string[]
     */
    public function getField2(): array
    {
        return $this->field2;
    }

    public function getField4(): \DateTimeInterface
    {
        return $this->field4;
    }

    public function isField3(): bool
    {
        return $this->field3;
    }

    public static function create(): self
    {
        return new self();
    }

    public function withField1(string $field1): self
    {
        $this->field1 = $field1;

        return $this;
    }

    public function withField2(array $field2): self
    {
        $this->field2 = $field2;

        return $this;
    }

    public function withField3(bool $field3): self
    {
        $this->field3 = $field3;

        return $this;
    }

    public function withField4(\DateTimeInterface $field4): self
    {
        $this->field4 = $field4;

        return $this;
    }
}
