<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\Controller\Web\Domain\SubDomain;

use OC\BusinessRules\Gateways\Pagination;
use OC\BusinessRules\Responders\PaginatedUseCaseResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class ListEntitiesController extends Controller
{
    public function getAllEntitiesAction(Request $request)
    {
        $response = $this->getEntities($request);

        $vm = $this->buildVM($response);

        return $this->render('', ['vm' => $vm]);
    }

    private function getEntities(Request $request): PaginatedUseCaseResponse
    {
        return $this->get('oc.use_cases.domain.sub_domain.get_all_entities')->execute(
            $this->get('oc.requestors.domain.sub_domain.get_all_entities_request_builder')
                ->create()
                ->withItemsPerPage(Pagination::ITEMS_PER_PAGE_ADMIN)
                ->withPage($request->get('page', 1))
                ->build()
        );
    }

    private function buildVM(PaginatedUseCaseResponse $response): ListEntities
    {
        return $this->get('oc.view_models.web.domain.sub_domain.list_entities_builder')
            ->create()
            ->withEntities(
                $this->get('oc.view_models.web.domain.sub_domain.entity_list_item_assembler')
                    ->createFromCollection($response->getItems())
            )
            ->withPagination(
                $this->get('oc.view_models.pagination.pagination_factory')
                    ->createFromPaginatedUseCaseResponse($response, 'oc_web_domain_sub_domain_entity_list')
            )
            ->build();
    }
}
