<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\Form\Type\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\Form\Model\Domain\SubDomain\EditFunctionalEntityModel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\RouterInterface;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class EditFunctionalEntityType extends AbstractType
{
    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("stringField", TextType::class, ['required' => true,])
            ->setAction($this->router->generate('oc_web_domain_sub_domain_show_functional_entity', ['id' => $options['id']]));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setRequired('id')
            ->setDefaults(['data_class' => EditFunctionalEntityModel::class]);
    }

    public function setRouter(RouterInterface $router)
    {
        $this->router = $router;
    }
}
