<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\BusinessRules\UseCases\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GenericUseCaseRequest;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\GenericUseCase;
use PHPUnit\Framework\TestCase;

final class GenericUseCaseTest extends TestCase
{
    private GenericUseCaseRequest $request;

    private GenericUseCase $useCase;

    /** @test */
    public function genericUseCaseReturnResponse(): void
    {
        $this->fail("TODO: Implement this test");
    }

    protected function setUp(): void
    {
        $this->request = $this->buildRequest();
        $this->useCase = new GenericUseCase();
    }

    private function buildRequest(): GenericUseCaseRequest
    {
        return GenericUseCaseRequest::create();
    }
}
