<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\BusinessRules\UseCases\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Gateways\Domain\SubDomain\Exceptions\FunctionalEntityNotFoundException;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntityRequest;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\GetFunctionalEntity;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Entities\Domain\SubDomain\FunctionalEntityStub1;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Gateways\Domain\SubDomain\InMemoryFunctionalEntityGateway;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseAssemblerMock;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseStub1;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseTestCase;
use PHPUnit\Framework\TestCase;

final class GetFunctionalEntityTest extends TestCase
{
    use FunctionalEntityDetailResponseTestCase;

    private GetFunctionalEntityRequest $request;

    private GetFunctionalEntity $useCase;

    /**
     * @test
     */
    public function functionalEntityNotFoundShouldThrowException(): void
    {
        $this->expectException(FunctionalEntityNotFoundException::class);

        $this->request->id = -1;
        $this->useCase->execute($this->request);
    }

    /**
     * @test
     */
    public function getFunctionalEntityShouldReturnResponse(): void
    {
        $response = $this->useCase->execute($this->request);

        $this->assertFunctionalEntityDetailResponse(new FunctionalEntityDetailResponseStub1(), $response);

        $this->fail("TODO: configure stub");
    }

    protected function setup(): void
    {
        $this->useCase = new GetFunctionalEntity(
            new FunctionalEntityDetailResponseAssemblerMock(),
            new InMemoryFunctionalEntityGateway([FunctionalEntityStub1::ID => new FunctionalEntityStub1()])
        );
        $this->request = GetFunctionalEntityRequest::create(FunctionalEntityStub1::ID);
    }
}
