<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\App\Entity\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Entities\Domain\SubDomain\FunctionalEntityFactory;

class FunctionalEntityFactoryImpl implements FunctionalEntityFactory
{
    /**
     * {@inheritdoc}
     */
    public function create()
    {
        return new FunctionalEntityImpl();
    }
}
