#!/usr/bin/php
<?php
/**
 * .git/hooks/pre-commit
 *
 * This pre-commit hooks will check for PHP error (lint), and make sure the code
 * is PSR compliant.
 *
 * Dependecy: PHP-CS-Fixer (https://github.com/fabpot/PHP-CS-Fixer)
 *
 * @author  Mardix  http://github.com/mardix
 * @since   Sept 4 2012
 *
 */
/**
 * collect all files which have been added, copied or
 * modified and store them in an array called output
 */
exec('git diff --cached --name-status --diff-filter=ACM', $output);
foreach ($output as $file) {
    $fileName = trim(substr($file, 1));
    /**
     * Only PHP file
     */
    if (pathinfo($fileName, PATHINFO_EXTENSION) == "php") {
        /**
         * Check for error
         */
        $lint_output = [];
        exec("php -l ".escapeshellarg($fileName), $lint_output, $return);
        if ($return == 0) {
            if(!file_exists('.php_cs.php')){
                exec('cp .php_cs.dist .php_cs.php');
                exec('chmod +x .php_cs.php');
            }
            /**
             * PHP-CS-Fixer && add it back
             */
            exec("vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix {$fileName} --show-progress=dots --verbose --allow-risky=yes --config=.php_cs.php; git add {$fileName}");
        } else {
            echo implode("\n", $lint_output), "\n";

            exit(1);

        }
    }
}
exit(0);
