<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Response;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityListItemResponse;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityListItemResponseDTO extends FunctionalEntityResponseDTO implements FunctionalEntityListItemResponse
{
}
