<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Response\FunctionalEntityListItemResponseDTO;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Entities\Domain\SubDomain\FunctionalEntityStub2;

class FunctionalEntityListItemResponseStub2 extends FunctionalEntityListItemResponseDTO
{
    public const FIELD_1 = FunctionalEntityStub2::FIELD_1;

    public const FIELD_2 = FunctionalEntityStub2::FIELD_2;

    public const FIELD_3 = FunctionalEntityStub2::FIELD_3;

    public const ID = FunctionalEntityStub2::ID;

    public string $field1 = self::FIELD_1;

    public array $field2 = self::FIELD_2;

    public bool $field3 = self::FIELD_3;

    public int $id = self::ID;
}
