<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Response\FunctionalEntityDetailResponseDTO;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\Api\ViewModels\Domain\SubDomain\FunctionalEntityListItemStub1;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\BusinessRules\Entities\Domain\SubDomain\FunctionalEntityStub1;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityListItemResponseStub1 extends FunctionalEntityDetailResponseDTO
{
    const FIELD_1 = FunctionalEntityStub1::FIELD_1;

    const FIELD_2 = FunctionalEntityStub1::FIELD_2;

    const FIELD_3 = FunctionalEntityStub1::FIELD_3;

    const ID = FunctionalEntityStub1::ID;

    public $field1 = FunctionalEntityListItemStub1::FIELD_1;

    public $field2 = FunctionalEntityListItemStub1::FIELD_2;

    public $field3 = FunctionalEntityListItemStub1::FIELD_3;

    public $id = FunctionalEntityListItemStub1::ID;
}
