<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\Tests\Doubles\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityResponse;
use PHPUnit\Framework\Assert;

trait FunctionalEntityResponseTestCase
{
    private function assertFunctionalEntityResponse(
        FunctionalEntityResponse $expected,
        FunctionalEntityResponse $actual
    ): void {
        Assert::assertSame($expected->getField1(), $actual->getField1());
        Assert::assertSame($expected->getField2(), $actual->getField2());
        Assert::assertSame($expected->getId(), $actual->getId());
        Assert::assertSame($expected->isField3(), $actual->isField3());
    }
}
