<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Response\FunctionalEntityDetailResponseDTO;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\BusinessRules\Entities\Domain\SubDomain\FunctionalEntityStub1;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityDetailResponseStub1 extends FunctionalEntityDetailResponseDTO
{
    const FIELD_1 = FunctionalEntityStub1::FIELD_1;

    const FIELD_2 = FunctionalEntityStub1::FIELD_2;

    const FIELD_3 = FunctionalEntityStub1::FIELD_3;

    const FIELD_4 = FunctionalEntityStub1::FIELD_4;

    const ID = FunctionalEntityStub1::ID;

    public $field1 = self::FIELD_1;

    public $field2 = self::FIELD_2;

    public $field3 = self::FIELD_3;

    public $field4 = self::FIELD_4;

    public $id = self::ID;
}
