<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\UseCases\Domain\SubDomain\DTO\Response\FunctionalEntityResponseDTO;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\tests\Doubles\Api\ViewModels\Domain\SubDomain\FunctionalEntityStub1;

/**
 * @author Samuel Gomis <gomis.samuel@external.openclassrooms.com>
 */
class FunctionalEntityResponseStub1 extends FunctionalEntityResponseDTO
{
    public $field1 = FunctionalEntityStub1::FIELD_1;

    public $field2 = FunctionalEntityStub1::FIELD_2;

    public $field3 = FunctionalEntityStub1::FIELD_3;

    public $id = FunctionalEntityStub1::ID;
}
