<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\Controller\Web\Domain\SubDomain\Admin;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\App\ViewModels\Web\Domain\SubDomain\ShowFunctionalEntity;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityNotFoundException;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class ShowFunctionalEntityController extends Controller
{
    public function showFunctionalEntityAction(int $id): Response
    {
        try {
            $functionalEntity = $this->getFunctionalEntity($id);
            $vm = $this->buildVm($functionalEntity);

            return $this->render('', ['vm' => $vm]);
        } catch (FunctionalEntityNotFoundException $nfe) {
            throw $this->createNotFoundException($id);
        }
    }

    private function getFunctionalEntity(int $id): FunctionalEntityDetailResponse
    {
        return $this->get('oc.business_rules.use_cases.domain.sub_domain.get_functional_entity')
            ->execute(
                $this->get('oc.business_rules.requestors.domain.sub_domain.get_functional_entity_request_builder')
                    ->create()
                    ->withFunctionalEntityId($id)
                    ->build()
            );
    }

    private function buildVm(FunctionalEntityDetailResponse $functionalEntity): ShowFunctionalEntity
    {
        return
            $this->get('oc.app.view_models.web.domain.sub_domain.show_functional_entity_builder')
                ->create()
                ->withFunctionalEntityDetail($this->get('oc.app.view_models.web.domain.sub_domain.functional_entity_detail_assembler')->createDetail($functionalEntity))
                ->build();
    }
}
