<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface CreateFunctionalEntityRequestBuilder extends UseCaseRequest
{
    public function build(): CreateFunctionalEntityRequest;

    public function create(): CreateFunctionalEntityRequestBuilder;

    public function withField1(string $field1): CreateFunctionalEntityRequestBuilder;

    public function withField2(array $field2): CreateFunctionalEntityRequestBuilder;

    public function withField3(bool $field3): CreateFunctionalEntityRequestBuilder;

    public function withField4(\DateTimeInterface $field4): CreateFunctionalEntityRequestBuilder;
}
