<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface DeleteFunctionalEntityRequestBuilder extends UseCaseRequest
{
    public function build(): DeleteFunctionalEntityRequest;

    public function create(): DeleteFunctionalEntityRequestBuilder;

    public function withFunctionalEntityId(int $id): DeleteFunctionalEntityRequestBuilder;
}
