<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface GenericUseCaseRequestBuilder extends UseCaseRequest
{
    public function build(): GenericUseCaseRequest;

    public function create(): GenericUseCaseRequestBuilder;
}
