<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface GetFunctionalEntityRequestBuilder extends UseCaseRequest
{
    public function create(): GetFunctionalEntityRequestBuilder;

    public function withFunctionalEntityId(int $id): GetFunctionalEntityRequestBuilder;

    public function build(): GetFunctionalEntityRequest;
}
