<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

/**
 * @author authorStub <author.stub@example.com>
 */
interface GetGenericUseCaseRequestBuilder extends UseCaseRequest
{
    public function create(): GetGenericUseCaseRequestBuilder;

    public function withGenericUseCaseId(int $id): GetGenericUseCaseRequestBuilder;

    public function build(): GetGenericUseCaseRequest;
}
