<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Requestors\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

/**
 * @author authorStub <author.stub@example.com>
 */
interface GetGenericUseCasesRequestBuilder extends UseCaseRequest
{
    public function create(): GetGenericUseCasesRequestBuilder;

    public function withFilters(array $filters = []): GetGenericUseCasesRequestBuilder;

    public function withItemsPerPage(int $itemsPerPage): GetGenericUseCasesRequestBuilder;

    public function withPage(int $page = 1): GetGenericUseCasesRequestBuilder;

    public function withSort(array $sort = []): GetGenericUseCasesRequestBuilder;

    public function build(): GetGenericUseCasesRequest;
}
