<?php declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\UseCases\Impl;

use OpenClassrooms\CodeGenerator\SkeletonModels\BusinessRules\UseCases\DeleteEntityUseCaseRequestBuilderImplSkeletonModel;

class DeleteEntityUseCaseRequestBuilderImplSkeletonModelImpl extends DeleteEntityUseCaseRequestBuilderImplSkeletonModel
{
}
