<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\UseCase\BusinessRules\Entities\PaginatedCollection;
use OpenClassrooms\UseCase\BusinessRules\Responders\PaginatedUseCaseResponse;

/**
 * @author authorStub <author.stub@example.com>
 */
interface FunctionalEntityListItemResponseAssembler
{
    public function createPaginatedCollection(PaginatedCollection $collection): PaginatedUseCaseResponse;
}
