<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain;

interface FunctionalEntityDetailResponse extends FunctionalEntityResponse
{
    public function getField4(): ?\DateTimeImmutable;
}
