<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\PaginatedUseCaseResponse;
use OpenClassrooms\UseCase\BusinessRules\Entities\PaginatedCollection;

interface FunctionalEntityListItemResponseAssembler
{
    public function createPaginatedCollection(PaginatedCollection $collection): PaginatedUseCaseResponse;
}
