<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\UseCaseResponse;

interface FunctionalEntityResponse extends UseCaseResponse
{
    public function getField1(): string;

    /**
     * @return string[]
     */
    public function getField2(): array;

    public function getId(): int;

    public function isField3(): bool;
}
