<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Responders\UseCaseResponse;

/**
 * @author authorStub <author.stub@example.com>
 */
interface FunctionalEntityResponse extends UseCaseResponse
{
    public function getId(): int;

    public function getField1(): string;

    /**
     * @return string[]
     */
    public function getField2(): array;

    public function isField3(): bool;
}
