<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain\GetEntityRequest;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain\GetEntityRequestBuilder;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class GetEntityRequestBuilderImpl implements GetEntityRequestBuilder
{
    /**
     * @var \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\Domain\SubDomain\DTO\Request\GetEntityRequestDTO
     */
    private $request;

    public function create(): GetEntityRequestBuilder
    {
        $this->request = new GetEntityRequestDTO();

        return $this;
    }

    public function withId(int $id): GetEntityRequestBuilder
    {
        $this->request->id = $id;

        return $this;
    }

    public function build(): GetEntityRequest
    {
        return $this->request;
    }
}
