<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntityRequest;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntityRequestBuilder;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class GetFunctionalEntityRequestBuilderImpl implements GetFunctionalEntityRequestBuilder
{
    /**
     * @var \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\Domain\SubDomain\DTO\Request\GetFunctionalEntityRequestDTO
     */
    private $request;

    public function create(): GetFunctionalEntityRequestBuilder
    {
        $this->request = new GetFunctionalEntityRequestDTO();

        return $this;
    }

    public function withId(int $id): GetFunctionalEntityRequestBuilder
    {
        $this->request->id = $id;

        return $this;
    }

    public function build(): GetFunctionalEntityRequest
    {
        return $this->request;
    }
}
