<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\EntityGateway;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\UseCaseRequest;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\EntityDetailResponseAssembler;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\UseCase;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class GetEntity implements UseCase
{
    /**
     * @var \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\EntityGateway
     */
    private $entityGateway;

    /**
     * @var \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\EntityDetailResponseAssembler
     */
    private $entityDetailResponseAssembler;

    /**
     * {@inheritdoc}
     * @param \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain\GetEntityRequest|UseCaseRequest $useCaseRequest
     *
     * @throws \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\EntityNotFoundException
     *
     * @return \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\EntityDetailResponse
     */
    public function execute(UseCaseRequest $useCaseRequest)
    {
        $entity = $this->entityGateway->find($useCaseRequest->getId());

        return $this->entityDetailResponseAssembler->create($entity);
    }

    public function setEntityGateway(EntityGateway $entityGateway)
    {
        $this->entityGateway = $entityGateway;
    }

    public function setEntityDetailResponseAssembler(EntityDetailResponseAssembler $entityDetailResponseAssembler)
    {
        $this->entityDetailResponseAssembler = $entityDetailResponseAssembler;
    }
}
