<?php
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityGateway;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\UseCaseRequest;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseAssembler;
use OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\UseCases\UseCase;

/**
 * @author Romain Kuzniak <romain.kuzniak@openclassrooms.com>
 */
class GetFunctionalEntity implements UseCase
{
    /**
     * @var \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityGateway
     */
    private $functionalEntityGateway;

    /**
     * @var \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponseAssembler
     */
    private $functionalEntityDetailResponseAssembler;

    /**
     * {@inheritdoc}
     * @param \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Requestors\Domain\SubDomain\GetFunctionalEntityRequest|UseCaseRequest $useCaseRequest
     *
     * @throws \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityNotFoundException
     *
     * @return \OpenClassrooms\CodeGenerator\Tests\Doubles\src\BusinessRules\Responders\Domain\SubDomain\FunctionalEntityDetailResponse
     */
    public function execute(UseCaseRequest $useCaseRequest)
    {
        $functionalEntity = $this->functionalEntityGateway->find($useCaseRequest->getId());

        return $this->functionalEntityDetailResponseAssembler->create($functionalEntity);
    }

    public function setFunctionalEntityGateway(FunctionalEntityGateway $functionalEntityGateway)
    {
        $this->functionalEntityGateway = $functionalEntityGateway;
    }

    public function setFunctionalEntityDetailResponseAssembler(FunctionalEntityDetailResponseAssembler $functionalEntityDetailResponseAssembler)
    {
        $this->functionalEntityDetailResponseAssembler = $functionalEntityDetailResponseAssembler;
    }
}
