<?php declare(strict_types=1);
// Auto Generated by OpenClassrooms Code Generator

namespace OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\App\Repository\Domain\SubDomain;

use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Entities\Domain\SubDomain\FunctionalEntity;
use OpenClassrooms\CodeGenerator\Tests\Fixtures\Classes\BusinessRules\Gateways\Domain\SubDomain\FunctionalEntityGateway;

/**
 * @author authorStub <author.stub@example.com>
 */
class FunctionalEntityRepository implements FunctionalEntityGateway
{
    public function find($id): FunctionalEntity
    {
        // TODO: Implement find() method.
    }

    public function findAll(array $filters = [], array $sorts = [], array $pagination = []): iterable
    {
        // TODO: Implement findAll() method.
    }

    public function insert(FunctionalEntity $functionalEntity): void
    {
        // TODO: Implement insert() method.
    }
}
