on: push
name: CodeGenerator
env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
    symfony:
        name: PHP - Tests & Coverage
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.4
                  extensions: mbstring, xml, ctype, iconv, pgsql, apcu
                  coverage: pcov
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Prepare
              run: |
                  composer install --no-scripts --no-interaction
            - name: Run tests
              run: |
                  bin/phpunit --coverage-clover build/logs/clover.xml -d memory_limit=2G
            - name: Clean
              run: |
                  bash <(curl -s https://codecov.io/bash)
